crds:
  keep: false

global:
  logging:
    format: json
    # -- Set the global logging level. One of: `debug`, `info`, `warn` or `error`
    level: info

controller:
  replicas: 1

configs:
  params:
    server.insecure: true

  repositories:
    serg-repo:
      url: https://github.com/Sergobeso/learn-devops
      name: serg
      type: git

  secret:
    # -- Bcrypt hashed admin password
    ## Argo expects the password in the secret to be bcrypt hashed. You can create this hash with
    ## `htpasswd -nbBC 10 "" $ARGO_PWD | tr -d ':\n' | sed 's/$2y/$2a/'`
    argocdServerAdminPassword: "$2a$10$OoqXCeK8E55IKLHOgHvrnuyVu2.U.JdZdAUrUM.jIWsB.PdUdSu8G%"

## Redis
redis:
  enabled: true

## Server
server:
  name: server
  replicas: 1

  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: "argocd-issuer"
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
    ingressClassName: "system-ingress"
    hostnames:
      - argocd.serg.local
    tls: true
