apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: system-ingress-controller
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: system-utils
  source:
    repoURL: 'https://github.com/Sergobeso/learn-devops'
    path: stepbystep/04argocd/argocd/01-clusterapp/03-ingress-nginx
    targetRevision: main
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: ingress-nginx
  syncPolicy:
    syncOptions:
      - CreateNamespace=true